### PR TITLE
Tutorial: How to enable dynamic rate limiting based on time

### PR DESCRIPTION
**Pull request by Guaris**
Tried to port this [doc](https://docs.konghq.com/hub/kong-inc/rate-limiting-advanced/how-to/peak-traffic-rate-limit/) and got stuck

### CODE REVIEW

**Comment by lena-larionova** [comment]
Q: What did you get stuck on? Testing + making it actually work?

**Comment by Guaris** [comment]
@lena-larionova all of the snippets render like this
image

**Comment by fabianrbz** [comment]
@Guaris remove `admin-api` from the tools section

the `entity_example` block renders the snippet in each format specified in `tools`

**Comment by lena-larionova** [comment]
@Guaris can you rebase, add a validation step, and apply the latest formatting?

**Pull request closed without merging**
