### PR TITLE
Insomnia: Security & FAQ page

### PR DESCRIPTION
**Pull request by cloudjumpercat**
Notes:
- Originally, we talked about this being a landing page. There's a lot of content here, so I've made it a reference for now, but content could move to other pages or be condensed, so this might change.

Preview URLs: 
- [Main Security landing page](https://deploy-preview-119--kongdeveloper.netlify.app/insomnia/security/)
  - [Data security](https://deploy-preview-119--kongdeveloper.netlify.app/insomnia/data-security/)
  - [Infrastructure security](https://deploy-preview-119--kongdeveloper.netlify.app/insomnia/infrastructure-security/)
  - [Collected data](https://deploy-preview-119--kongdeveloper.netlify.app/insomnia/collected-data/)
  - [Incident response](https://deploy-preview-119--kongdeveloper.netlify.app/insomnia/incident-response/)
  - [SSO](https://deploy-preview-119--kongdeveloper.netlify.app/insomnia/sso/)
  - [RBAC](https://deploy-preview-119--kongdeveloper.netlify.app/insomnia/rbac/)
  - [Storage options](https://deploy-preview-119--kongdeveloper.netlify.app/insomnia/storage-options/)

TODO:
- [x] Make more of the content into FAQ for readability (unconventional for a SEC doc, but I think this will work better than a wall of text)
- [x] Separate FAQ by section (this is possible in a landing page...)
- [ ] Revise all content (currently, this is just copy/pasted from sources to get the content in the right format first, will do a copyedit after the security meeting on Friday)
- [x] Create links from other pages to this page

### CODE REVIEW

**Comment by Guaris** [comment]
I have a few questions: 
* Is security a core component of Insomnia? i seem to remember that security is the one place where we can beat out Postman. 
   * If the answer is yes, then is there anything we are missing out on by not having a security landing page? 
* From your PR I am getting that the core elements security at Insomnia are[Data security](https://deploy-preview-119--kongdeveloper.netlify.app/insomnia/security/#data-security), [Infrastructure security](https://deploy-preview-119--kongdeveloper.netlify.app/insomnia/security/#infrastructure-security), [Collected data](https://deploy-preview-119--kongdeveloper.netlify.app/insomnia/security/#collected-data), [Incident response and vulnerability management](https://deploy-preview-119--kongdeveloper.netlify.app/insomnia/security/#incident-response-and-vulnerability-management). Are these pieces related enough that the end user expects to see everything in one page? 
* What does “stored” and “locked” mean and if I don’t know what they means where should I go to learn? 
* Does this still adhere to every page is page one? 

>Why per section FAQs? They're a bit non-traditional for a security page, but I think I prefer the info displayed that way. It's easier to digest and find what you need than the typical sec page that has paragraphs and paragraphs of content you have to weed through and can't skim. What does everyone else think?

I don't really have an opinion on the FAQs per section, but I do have a question: 

* I think this is the first time we've featured FAQs on a reference page. By doing this here it means we can now do FAQs in all reference pages. Do you think that could become a problem in the future? Specifically because we are trying to train users to expect certain things on certain pages, if they get an FAQ on a reference page and they like it, they may expect FAQs on every reference page they visit. What do you think?

**Comment by cloudjumpercat** [comment]
@Guaris Great feedback!

> * Is security a core component of Insomnia? i seem to remember that security is the one place where we can beat out Postman.

From my understanding, it's the flexibility of the security. As in you can do git sync, cloud sync, and local storage (scratch pad). Some users didn't want their API client storing their data, so scratch pad is what they want, which Postman doesn't offer. That being said, I think I can do a better job of highlighting that in this doc.

> From your PR I am getting that the core elements security at Insomnia are[Data security](https://deploy-preview-119--kongdeveloper.netlify.app/insomnia/security/#data-security), [Infrastructure security](https://deploy-preview-119--kongdeveloper.netlify.app/insomnia/security/#infrastructure-security), [Collected data](https://deploy-preview-119--kongdeveloper.netlify.app/insomnia/security/#collected-data), [Incident response and vulnerability management](https://deploy-preview-119--kongdeveloper.netlify.app/insomnia/security/#incident-response-and-vulnerability-management). Are these pieces related enough that the end user expects to see everything in one page?

I pulled some of those titles from the Postman sec doc: https://www.postman.com/trust/security/ . This is a good point, I have an understanding of what sec users would want based on sec docs I've written in the past, but maybe the old "format" needs to be revisited. Would this be a good opportunity to reach out to our SEC team and see what they think of the doc, or best to save that for later? I know when I wrote sec guides in the past, typically the end user is an [Executive](https://docs.google.com/document/d/1HNmHOwVBeVcF1TqvCgxv4M7QGt7GNmPip3VC2GC_huQ/edit?tab=t.0#bookmark=kix.wxoafbgrv8h3) or [Security Owner](https://docs.google.com/document/d/1HNmHOwVBeVcF1TqvCgxv4M7QGt7GNmPip3VC2GC_huQ/edit?tab=t.0#bookmark=kix.vy8azxqqdp7f) who wants a one stop shop for all things security, they don't really want to link off to a bunch of other pages or hunt for the different features. They're used to a security one pager for a product. My experience in the past was that they want to know about the encryption, data collected, and where data is stored and how (like AWS buckets/regions), just as big overall topics. 

> What does “stored” and “locked” mean and if I don’t know what they means where should I go to learn?

Good call out, I meant to ask the Insomnia team since some features in the table had a 🔒 emoji next to them and I didn't really know what it meant.

> Does this still adhere to every page is page one?

For the most part, yes, security users want all the info on one page. I go back and forth on the storage options. They relate to security, but they also relate to IC users who are just using the product. Maybe I need to think about splitting those where the sec content is on this page and there's a separate page for ICs. 

> I think this is the first time we've featured FAQs on a reference page. By doing this here it means we can now do FAQs in all reference pages. Do you think that could become a problem in the future? Specifically because we are trying to train users to expect certain things on certain pages, if they get an FAQ on a reference page and they like it, they may expect FAQs on every reference page they visit. What do you think?

I can see where this could be a problem. I think there is such a thing as too many FAQ and where long form content is needed over a FAQ. But if users find value in FAQ, I think we should make them when it works. Technically, FAQ are allowed on reference and concept pages at the moment, it's just that they'd be in the metadata and then appear as a FAQ section at the bottom of the page.

I know we already have established the ability to do per section FAQ on landing pages, but I don't think (based on my experience/current understanding of sec docs) that users want to be routed to different pages, they want all the info on one page. Which didn't seem like the landing pages we currently have.

**Comment by cloudjumpercat** [comment]
Update: I decided to reach out to Tom in Legal about some general security questions to see what these users are looking for and need in security docs.

**Comment by fabianrbz** [comment]
I do think we can benefit from an Insomnia security landing page, where we can highlight the security features (using cards maybe?) and link to specific pages, e.g.:
* Data Security
* Infra security
* collected data
* etc.

That way users can have a general idea of what Insomnia supports,  and go to the individual pages for more information.
I think you can split up your existing page into multiple ones, e.g. the Data Security section could be a page (it isn't related to the rest of the sections), all the relevant info about it lives there and it's self contained.

**Comment by cloudjumpercat** [comment]
@Guaris @fabianrbz Thanks for the feedback! I turned this into a landing page and broke the sections into their own pages:

- [Main Security landing page](https://deploy-preview-119--kongdeveloper.netlify.app/insomnia/security/)
  - [Data security](https://deploy-preview-119--kongdeveloper.netlify.app/insomnia/data-security/)
  - [Infrastructure security](https://deploy-preview-119--kongdeveloper.netlify.app/insomnia/infrastructure-security/)
  - [Collected data](https://deploy-preview-119--kongdeveloper.netlify.app/insomnia/collected-data/)
  - [Incident response](https://deploy-preview-119--kongdeveloper.netlify.app/insomnia/incident-response/)
  - [SSO](https://deploy-preview-119--kongdeveloper.netlify.app/insomnia/sso/)
  - [RBAC](https://deploy-preview-119--kongdeveloper.netlify.app/insomnia/rbac/)
  - [Storage options](https://deploy-preview-119--kongdeveloper.netlify.app/insomnia/storage-options/)

Let me know what you think of this option! I haven't copyedited text yet, I plan to do that once we know if this is the right direction and once I hear back from Legal if we need to add any additional info about security.

**Pull request merged**
