### PR TITLE
Add support for navtabs in landing pages

### PR DESCRIPTION
**Pull request by mheap**
See OSX, Windows, Linux on https://deploy-preview-52--kongdeveloper.netlify.app/deck/

### CODE REVIEW

**Comment by fabianrbz** [comment]
I should fix navtabs, to support a better way to render things,

Did  any of these `navtab {{ item.title }}` or `navtab item.title` work?

**Comment by mheap** [comment]
Yes, it works with braces

https://github.com/Kong/developer.konghq.com/pull/52/files#diff-0f6c67fa37bc6120fbd135bbf568c112cad4a60824289f6ff396a01f8893f964R3

**Comment by fabianrbz** [comment]
does it work without the double quotes?

**Comment by mheap** [comment]
It doesn’t due to the regex (I added additional error messaging to make it clearer)

**Comment by fabianrbz** [comment]
I'll see if I can fix that

**Review by fabianrbz — APPROVED** [review]

**Pull request merged**
